### ISSUE TITLE
Use a permissive license

### ISSUE THREAD

**Issue by jodal** [tamland/mopidy-banshee#1]
Is there any particular reason you've chosen GPLv3 as the license for Mopidy-Banshee?

Mopidy itself and all other available extensions use either the Apache license or the MIT license. Using GPLv3 for Mopidy-Banshee will prohibit using any code from it in Mopidy's core or any other extension. Also, we will not feature the extension in Mopidy's documentation, as stated in our extension development guide.

**Comment by tamland** [comment]
Didn't read that part of the documentation. I just generally prefer it by default that's all. I don't mind changing it. I don't see there should be any issue with _using_ it though.

**Comment by jodal** [comment]
You're welcome to use (almost) any license of your want. That said, with you choosing a more similar or exactly the same license as Mopidy removes some uncertainties and discussions around licenses.

Thanks!
